version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: sh -c "alembic upgrade head && gunicorn src.interfaces.api.app:app --bind 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker -w 2"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - "./backend/.env"
    volumes:
      - ./backend:/www/
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/healthcheck" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.tmp:/tmp
      - ./.docker/postgres:/var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 10240000000
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: http://localhost:8000
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/www
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
