"""create drugs table

Revision ID: b6e35bcacbd5
Revises: 
Create Date: 2025-04-17 23:26:07.040942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6e35bcacbd5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drugs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trade_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drugs', schema='public')
    # ### end Alembic commands ###
