"""obligation

Revision ID: b59e3a3c5199
Revises: abc5b19996f8
Create Date: 2025-05-09 18:20:06.172551

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b59e3a3c5199"
down_revision = "abc5b19996f8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("drugs", sa.Column("obligation", sa.String(), nullable=True))
    op.drop_column("drugs", "oblication")
    op.drop_constraint(
        "submission_rules_routename_fkey",
        "submission_rules",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "submission_rules",
        "drugs",
        ["routename"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.drop_constraint(
        "type_of_event_inn_id_fkey", "type_of_event", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "type_of_event",
        "submission_rules",
        ["inn_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        None, "type_of_event", schema="public", type_="foreignkey"
    )
    op.create_foreign_key(
        "type_of_event_inn_id_fkey",
        "type_of_event",
        "submission_rules",
        ["inn_id"],
        ["id"],
    )
    op.drop_constraint(
        None, "submission_rules", schema="public", type_="foreignkey"
    )
    op.create_foreign_key(
        "submission_rules_routename_fkey",
        "submission_rules",
        "drugs",
        ["routename"],
        ["id"],
    )
    op.add_column(
        "drugs",
        sa.Column(
            "oblication", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("drugs", "obligation")
    # ### end Alembic commands ###
