"""delete name from submission_rules

Revision ID: 15a3d9cc46e0
Revises: 1ec05016a43f
Create Date: 2025-05-09 18:38:24.705287

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "15a3d9cc46e0"
down_revision = "1ec05016a43f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "submission_rules_routename_fkey",
        "submission_rules",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "submission_rules",
        "drugs",
        ["routename"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.drop_column("submission_rules", "name")
    op.drop_constraint(
        "type_of_event_inn_id_fkey", "type_of_event", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "type_of_event",
        "submission_rules",
        ["inn_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        None, "type_of_event", schema="public", type_="foreignkey"
    )
    op.create_foreign_key(
        "type_of_event_inn_id_fkey",
        "type_of_event",
        "submission_rules",
        ["inn_id"],
        ["id"],
    )
    op.add_column(
        "submission_rules",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(
        None, "submission_rules", schema="public", type_="foreignkey"
    )
    op.create_foreign_key(
        "submission_rules_routename_fkey",
        "submission_rules",
        "drugs",
        ["routename"],
        ["id"],
    )
    # ### end Alembic commands ###
