"""obligation2

Revision ID: 1ec05016a43f
Revises: b59e3a3c5199
Create Date: 2025-05-09 18:32:29.487275

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1ec05016a43f"
down_revision = "b59e3a3c5199"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "submission_rules", sa.Column("name", sa.String(), nullable=True)
    )
    op.drop_constraint(
        "submission_rules_routename_fkey",
        "submission_rules",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "submission_rules",
        "drugs",
        ["routename"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.drop_constraint(
        "type_of_event_inn_id_fkey", "type_of_event", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "type_of_event",
        "submission_rules",
        ["inn_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        None, "type_of_event", schema="public", type_="foreignkey"
    )
    op.create_foreign_key(
        "type_of_event_inn_id_fkey",
        "type_of_event",
        "submission_rules",
        ["inn_id"],
        ["id"],
    )
    op.drop_constraint(
        None, "submission_rules", schema="public", type_="foreignkey"
    )
    op.create_foreign_key(
        "submission_rules_routename_fkey",
        "submission_rules",
        "drugs",
        ["routename"],
        ["id"],
    )
    op.drop_column("submission_rules", "name")
    # ### end Alembic commands ###
