"""submission

Revision ID: 9dc035d8be01
Revises: 3d267f0e2faf
Create Date: 2025-06-01 15:21:47.662595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dc035d8be01'
down_revision = '3d267f0e2faf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission_rule_drug',
    sa.Column('submission_rule_id', sa.UUID(), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.ForeignKeyConstraint(['submission_rule_id'], ['submission_rules.id'], ),
    sa.PrimaryKeyConstraint('submission_rule_id', 'drug_id')
    )
    op.add_column('submission_rules', sa.Column('valid_start_date', sa.DateTime(), nullable=True))
    op.add_column('submission_rules', sa.Column('valid_end_date', sa.DateTime(), nullable=True))
    op.drop_constraint('submission_rules_routename_fkey', 'submission_rules', type_='foreignkey')
    op.drop_column('submission_rules', 'routename')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission_rules', sa.Column('routename', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('submission_rules_routename_fkey', 'submission_rules', 'drugs', ['routename'], ['id'])
    op.drop_column('submission_rules', 'valid_end_date')
    op.drop_column('submission_rules', 'valid_start_date')
    op.drop_table('submission_rule_drug')
    # ### end Alembic commands ###
