"""alter submission_rules deadline_to_submit

Revision ID: b71a6ed9cf41
Revises: 15a3d9cc46e0
Create Date: 2025-05-10 13:12:03.630930

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b71a6ed9cf41"
down_revision = "15a3d9cc46e0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "submission_rules",
        "deadline_to_submit",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.Date(),
        existing_nullable=True,
    )
    op.drop_constraint(
        "submission_rules_routename_fkey",
        "submission_rules",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "submission_rules",
        "drugs",
        ["routename"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.drop_constraint(
        "type_of_event_inn_id_fkey", "type_of_event", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "type_of_event",
        "submission_rules",
        ["inn_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        None, "type_of_event", schema="public", type_="foreignkey"
    )
    op.create_foreign_key(
        "type_of_event_inn_id_fkey",
        "type_of_event",
        "submission_rules",
        ["inn_id"],
        ["id"],
    )
    op.drop_constraint(
        None, "submission_rules", schema="public", type_="foreignkey"
    )
    op.create_foreign_key(
        "submission_rules_routename_fkey",
        "submission_rules",
        "drugs",
        ["routename"],
        ["id"],
    )
    op.alter_column(
        "submission_rules",
        "deadline_to_submit",
        existing_type=sa.Date(),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
